/*
 * Copyright (c) 2026 MNFST, Inc.
 * Copyright (c) 2026 BlockRun
 * Modifications copyright (c) 2026 Sapience AI Corporation
 *
 * Portions of this file are derived from the Manifest project
 * (https://github.com/mnfst/manifest) and the ClawRouter project
 * (https://github.com/BlockRunAI/ClawRouter), both used under the MIT
 * License — see NOTICE for the full license text. This file has been
 * modified for use in the OpenClaw Middleware Suite.
 */

/**
 * Model Routing Middleware — Configuration
 * Defaults drawn from Manifest (23 dimensions), ClawRouter (boundaries, overrides),
 * and iblai (system prompt exclusion, hot-reload philosophy).
 */

import {
  ScoringConfig,
  TierModelConfig,
  Tier,
  DimensionDef,
  ProviderConfig,
  ClassifierConfig,
  DedupConfig,
} from './types.js';
import { MomentumConfig, DEFAULT_MOMENTUM_CONFIG } from './session/momentum.js';
import { SessionStoreConfig, DEFAULT_SESSION_STORE_CONFIG } from './session/session-store.js';
import { ResponseCacheConfig, DEFAULT_RESPONSE_CACHE_CONFIG } from './cache/response-cache.js';
import { CostAlertConfig, DEFAULT_COST_ALERT_CONFIG } from './storage/cost-tracker.js';
import { RoutingProfile, PROFILE_CONFIGS } from './selection/profiles.js';
import { getOpenAIApiKey, getOpenAIBaseUrl } from '../../shared/env.js';

// ---------------------------------------------------------------------------
// Full model-routing config shape
// ---------------------------------------------------------------------------

export interface ModelRoutingConfig {
  enabled: boolean;
  port: number;
  targetBaseUrl: string;
  targetApiKey: string;

  scoring: ScoringConfig;
  /** Per-profile tier-to-model mappings. The proxy looks up
   *  `tiersByProfile[resolvedProfile]` at request time. Each profile
   *  (`eco` / `premium` / `agentic`) carries its own primary + fallbacks
   *  per tier; profiles missing a slot inherit the static `PROFILE_CONFIGS`
   *  default. */
  tiersByProfile: Record<RoutingProfile, Record<Tier, TierModelConfig>>;

  /** Multi-provider connections (Phase 3) */
  providers: Record<string, ProviderConfig>;
  /** LLM fallback classifier for ambiguous requests (Phase 2) */
  classifier: ClassifierConfig;
  /** Request deduplication (Phase 2) */
  dedup: DedupConfig;
  /** Active model exclusions (populated from store at runtime) */
  exclusions: string[];

  /** Session momentum blending (Phase 4) */
  momentum: MomentumConfig;
  /** Session persistence with model pinning (Phase 4) */
  session: SessionStoreConfig;
  /** Default routing profile (Phase 4) */
  defaultProfile: RoutingProfile;

  /** Response caching (Phase 5) */
  responseCache: ResponseCacheConfig;
  /** Cost tracking alerts (Phase 5) */
  costAlerts: CostAlertConfig;
  /** Provider-level prompt caching (Anthropic cache_control markers today).
   *  Gated on session.enabled — caching without pinning wastes the markers
   *  because follow-ups may land on a different model with no cached prefix. */
  providerCache: ProviderCacheConfig;
}

// ---------------------------------------------------------------------------
// Provider prompt caching
// ---------------------------------------------------------------------------

export interface ProviderCacheConfig {
  /** When true, adapters attach provider-specific cache hints (Anthropic
   *  cache_control markers on system prompt + tool definitions). */
  enabled: boolean;
}

export const DEFAULT_PROVIDER_CACHE_CONFIG: ProviderCacheConfig = {
  enabled: true,
};

// ---------------------------------------------------------------------------
// Default keyword dimension definitions
// ---------------------------------------------------------------------------

// Multilingual keywords: EN + ZH + JA + RU + DE + ES + PT + KO + AR
// Translations sourced from ClawRouter where available.
const DEFAULT_KEYWORD_DIMENSIONS: DimensionDef[] = [
  // ── Keyword dimensions (14) ──────────────────────────────────────────────
  {
    kind: 'keyword',
    name: 'formalLogic',
    weight: 0.07,
    direction: 'up',
    keywords: [
      // English
      'prove',
      'proof',
      'derive',
      'derivation',
      'theorem',
      'lemma',
      'corollary',
      'if and only if',
      'iff',
      'contradiction',
      'contrapositive',
      'induction',
      'deduction',
      'axiom',
      'postulate',
      'qed',
      'formally verify',
      'satisfiability',
      'soundness',
      'completeness',
      'undecidable',
      'reducible',
      'irrational',
      'rational',
      'conjecture',
      'hypothesis',
      // Chinese
      '证明',
      '定理',
      '推导',
      '逐步',
      '思维链',
      '形式化',
      '数学',
      '逻辑',
      '公理',
      '矛盾',
      '归纳',
      '演绎',
      '猜想',
      '引理',
      // Japanese
      '証明',
      '定理',
      '導出',
      'ステップバイステップ',
      '論理的',
      '公理',
      '矛盾',
      // Russian
      'доказать',
      'докажи',
      'доказательств',
      'теорема',
      'вывести',
      'шаг за шагом',
      'пошагово',
      'поэтапно',
      'цепочка рассуждений',
      'рассуждени',
      'формально',
      'математически',
      'логически',
      'аксиома',
      // German
      'beweisen',
      'beweis',
      'theorem',
      'ableiten',
      'schritt für schritt',
      'gedankenkette',
      'formal',
      'mathematisch',
      'logisch',
      'axiom',
      // Spanish
      'demostrar',
      'teorema',
      'derivar',
      'paso a paso',
      'cadena de pensamiento',
      'formalmente',
      'matemático',
      'prueba',
      'lógicamente',
      // Portuguese
      'provar',
      'teorema',
      'derivar',
      'passo a passo',
      'cadeia de pensamento',
      'formalmente',
      'matemático',
      'prova',
      'logicamente',
      // Korean
      '증명',
      '정리',
      '도출',
      '단계별',
      '사고의 연쇄',
      '형식적',
      '수학적',
      '논리적',
      // Arabic
      'إثبات',
      'نظرية',
      'اشتقاق',
      'خطوة بخطوة',
      'سلسلة التفكير',
      'رسمياً',
      'رياضي',
      'برهان',
      'منطقياً',
    ],
  },
  {
    kind: 'keyword',
    name: 'analyticalReasoning',
    weight: 0.06,
    direction: 'up',
    keywords: [
      // English
      'compare',
      'contrast',
      'evaluate',
      'assess',
      'trade-offs',
      'tradeoffs',
      'pros and cons',
      'advantages and disadvantages',
      'weigh',
      'critically analyze',
      'strengths and weaknesses',
      'implications',
      'ramifications',
      'nuance',
      'on the other hand',
      'counterargument',
      'analyze',
      'analysis',
      'explain',
      // Chinese
      '比较',
      '对比',
      '评估',
      '权衡',
      '优缺点',
      '利弊',
      '分析',
      '含义',
      '反驳',
      // Japanese
      '比較',
      '対比',
      '評価',
      'トレードオフ',
      '長所と短所',
      '分析',
      '含意',
      // Russian
      'сравнить',
      'сравни',
      'оценить',
      'оцени',
      'взвесить',
      'плюсы и минусы',
      'преимущества и недостатки',
      'анализировать',
      'проанализируй',
      'нюанс',
      // German
      'vergleichen',
      'bewerten',
      'abwägen',
      'vor- und nachteile',
      'analysieren',
      // Spanish
      'comparar',
      'evaluar',
      'sopesar',
      'ventajas y desventajas',
      'analizar',
      // Portuguese
      'comparar',
      'avaliar',
      'ponderar',
      'vantagens e desvantagens',
      'analisar',
      // Korean
      '비교',
      '평가',
      '장단점',
      '분석',
      '함의',
      // Arabic
      'مقارنة',
      'تقييم',
      'موازنة',
      'إيجابيات وسلبيات',
      'تحليل',
    ],
  },
  {
    kind: 'keyword',
    name: 'codeGeneration',
    weight: 0.06,
    direction: 'up',
    keywords: [
      // English
      'write a function',
      'implement',
      'create a class',
      'build a component',
      'write code',
      'write a script',
      'code this',
      'program this',
      'create an api',
      'build a module',
      'scaffold',
      'boilerplate',
      'write a test',
      'write tests',
      'generate code',
      'component',
      'endpoint',
      'handler',
      'controller',
      'write a component',
      'create a component',
      'build a service',
      'implementing',
      'implemented',
      'implementation',
      // Code syntax tokens (universal + multilingual from ClawRouter)
      'function',
      'class',
      'import',
      'def',
      'SELECT',
      'async',
      'await',
      'const',
      'let',
      'var',
      'return',
      '```',
      // Chinese
      '函数',
      '类',
      '导入',
      '定义',
      '查询',
      '异步',
      '等待',
      '常量',
      '变量',
      '返回',
      '写一个函数',
      '实现',
      '创建类',
      '写代码',
      '生成代码',
      // Japanese
      '関数',
      'クラス',
      'インポート',
      '非同期',
      '定数',
      '変数',
      'コードを書く',
      '実装',
      // Russian
      'функция',
      'класс',
      'импорт',
      'определ',
      'запрос',
      'асинхронный',
      'ожидать',
      'константа',
      'переменная',
      'вернуть',
      'написать функцию',
      'реализовать',
      'написать код',
      // German
      'funktion',
      'klasse',
      'importieren',
      'definieren',
      'abfrage',
      'asynchron',
      'erwarten',
      'konstante',
      'variable',
      'zurückgeben',
      // Spanish
      'función',
      'clase',
      'importar',
      'definir',
      'consulta',
      'asíncrono',
      'esperar',
      'constante',
      'retornar',
      'escribir una función',
      'implementar',
      'escribir código',
      // Portuguese
      'função',
      'classe',
      'importar',
      'definir',
      'consulta',
      'assíncrono',
      'aguardar',
      'constante',
      'variável',
      'retornar',
      'escrever uma função',
      'implementar',
      'escrever código',
      // Korean
      '함수',
      '클래스',
      '가져오기',
      '정의',
      '쿼리',
      '비동기',
      '대기',
      '상수',
      '변수',
      '반환',
      '코드 작성',
      '구현',
      // Arabic
      'دالة',
      'فئة',
      'استيراد',
      'تعريف',
      'استعلام',
      'غير متزامن',
      'انتظار',
      'ثابت',
      'متغير',
      'إرجاع',
      'كتابة كود',
    ],
  },
  {
    kind: 'keyword',
    name: 'codeReview',
    weight: 0.05,
    direction: 'up',
    keywords: [
      // English
      'fix this bug',
      'debug',
      'why does this fail',
      'review this code',
      "what's wrong with",
      'code review',
      'refactor',
      'optimize this code',
      'find the error',
      'stack trace',
      'exception',
      'segfault',
      'memory leak',
      'race condition',
      'deadlock',
      'off by one',
      'typeerror',
      'referenceerror',
      'syntaxerror',
      'vulnerabilities',
      'vulnerability',
      // Chinese
      '修复',
      '调试',
      '代码审查',
      '重构',
      '优化代码',
      '找错误',
      '堆栈跟踪',
      '内存泄漏',
      // Japanese
      'デバッグ',
      'コードレビュー',
      'リファクタリング',
      'スタックトレース',
      'メモリリーク',
      // Russian
      'исправить баг',
      'отладить',
      'отладка',
      'дебаг',
      'рефакторинг',
      'ревью кода',
      'оптимизировать код',
      'стек вызовов',
      'утечка памяти',
      // German
      'fehlerbehebung',
      'debuggen',
      'code-review',
      'refaktorisieren',
      'code optimieren',
      'speicherleck',
      // Spanish
      'depurar',
      'revisión de código',
      'refactorizar',
      'optimizar código',
      'fuga de memoria',
      // Portuguese
      'depurar',
      'revisão de código',
      'refatorar',
      'otimizar código',
      'vazamento de memória',
      // Korean
      '디버그',
      '코드 리뷰',
      '리팩토링',
      '코드 최적화',
      '메모리 누수',
      // Arabic
      'تصحيح',
      'مراجعة الكود',
      'إعادة هيكلة',
      'تحسين الكود',
      'تسرب الذاكرة',
    ],
  },
  {
    kind: 'keyword',
    name: 'technicalTerms',
    weight: 0.07,
    direction: 'up',
    keywords: [
      // English
      'algorithm',
      'kubernetes',
      'distributed',
      'microservice',
      'database',
      'architecture',
      'infrastructure',
      'deployment',
      'pipeline',
      'middleware',
      'encryption',
      'authentication',
      'authorization',
      'latency',
      'throughput',
      'concurrency',
      'parallelism',
      'serialization',
      'deserialization',
      'react',
      'graphql',
      'typescript',
      'docker',
      'sql',
      'redis',
      'frontend',
      'backend',
      'server',
      'api',
      'oauth',
      'repositories',
      'repository',
      'security',
      // Chinese
      '算法',
      '优化',
      '架构',
      '分布式',
      '微服务',
      '数据库',
      '基础设施',
      '加密',
      '认证',
      '授权',
      '延迟',
      '吞吐量',
      '并发',
      // Japanese
      'アルゴリズム',
      '最適化',
      'アーキテクチャ',
      '分散',
      'マイクロサービス',
      'データベース',
      // Russian
      'алгоритм',
      'оптимизировать',
      'оптимизаци',
      'архитектура',
      'распределённый',
      'микросервис',
      'база данных',
      'инфраструктура',
      // German
      'algorithmus',
      'optimieren',
      'architektur',
      'verteilt',
      'mikroservice',
      'datenbank',
      'infrastruktur',
      // Spanish
      'algoritmo',
      'optimizar',
      'arquitectura',
      'distribuido',
      'microservicio',
      'base de datos',
      'infraestructura',
      // Portuguese
      'algoritmo',
      'otimizar',
      'arquitetura',
      'distribuído',
      'microsserviço',
      'banco de dados',
      'infraestrutura',
      // Korean
      '알고리즘',
      '최적화',
      '아키텍처',
      '분산',
      '마이크로서비스',
      '데이터베이스',
      '인프라',
      // Arabic
      'خوارزمية',
      'تحسين',
      'بنية',
      'موزع',
      'خدمة مصغرة',
      'قاعدة بيانات',
      'بنية تحتية',
    ],
  },
  {
    kind: 'keyword',
    name: 'simpleIndicators',
    weight: 0.08,
    direction: 'down',
    keywords: [
      // English
      'what is',
      'define',
      'translate',
      'thanks',
      'thank you',
      'yes',
      'no',
      'ok',
      'okay',
      'sure',
      'got it',
      'hi',
      'hello',
      'hey',
      'bye',
      'goodbye',
      'how are you',
      'good morning',
      'good night',
      'please',
      'help',
      'what time',
      'where is',
      'who is',
      // Chinese
      '什么是',
      '定义',
      '翻译',
      '你好',
      '是否',
      '首都',
      '多大',
      '谁是',
      '何时',
      // Japanese
      'とは',
      '定義',
      '翻訳',
      'こんにちは',
      'はいかいいえ',
      '首都',
      '誰',
      // Russian
      'что такое',
      'определение',
      'перевести',
      'переведи',
      'привет',
      'да или нет',
      'столица',
      'сколько лет',
      'кто такой',
      'когда',
      'объясни',
      // German
      'was ist',
      'definiere',
      'übersetze',
      'hallo',
      'ja oder nein',
      'hauptstadt',
      'wie alt',
      'wer ist',
      'wann',
      'erkläre',
      // Spanish
      'qué es',
      'definir',
      'traducir',
      'hola',
      'sí o no',
      'capital de',
      'cuántos años',
      'quién es',
      'cuándo',
      // Portuguese
      'o que é',
      'definir',
      'traduzir',
      'olá',
      'sim ou não',
      'capital de',
      'quantos anos',
      'quem é',
      'quando',
      // Korean
      '무엇',
      '정의',
      '번역',
      '안녕하세요',
      '예 또는 아니오',
      '수도',
      '누구',
      '언제',
      // Arabic
      'ما هو',
      'تعريف',
      'ترجم',
      'مرحبا',
      'نعم أو لا',
      'عاصمة',
      'من هو',
      'متى',
    ],
  },
  {
    kind: 'keyword',
    name: 'multiStep',
    weight: 0.07,
    direction: 'up',
    keywords: [
      // English
      'first',
      'then',
      'after that',
      'finally',
      'step 1',
      'step 2',
      'step 3',
      'next',
      'subsequently',
      'once you',
      'followed by',
      'in sequence',
      'phase 1',
      'phase 2',
      'stage 1',
      'stage 2',
      'workflow',
      'pipeline',
      // Chinese
      '首先',
      '然后',
      '之后',
      '最后',
      '第一步',
      '第二步',
      '第三步',
      '接下来',
      '工作流',
      // Japanese
      'まず',
      'それから',
      '最後に',
      'ステップ1',
      'ステップ2',
      '次に',
      'ワークフロー',
      // Russian
      'сначала',
      'потом',
      'затем',
      'после этого',
      'наконец',
      'далее',
      'шаг 1',
      'шаг 2',
      'шаг 3',
      // German
      'zuerst',
      'dann',
      'danach',
      'schließlich',
      'schritt 1',
      'schritt 2',
      'als nächstes',
      // Spanish
      'primero',
      'luego',
      'después',
      'finalmente',
      'paso 1',
      'paso 2',
      'a continuación',
      // Portuguese
      'primeiro',
      'depois',
      'em seguida',
      'finalmente',
      'passo 1',
      'passo 2',
      // Korean
      '먼저',
      '그 다음',
      '마지막으로',
      '단계 1',
      '단계 2',
      '다음으로',
      '워크플로',
      // Arabic
      'أولاً',
      'ثم',
      'بعد ذلك',
      'أخيراً',
      'الخطوة 1',
      'الخطوة 2',
      'التالي',
    ],
  },
  {
    kind: 'keyword',
    name: 'creative',
    weight: 0.03,
    direction: 'up',
    keywords: [
      // English
      'story',
      'poem',
      'creative',
      'brainstorm',
      'imagine',
      'fiction',
      'narrative',
      'character',
      'plot',
      'dialogue',
      'write a song',
      'compose',
      'artistic',
      'metaphor',
      'allegory',
      // Chinese
      '故事',
      '诗',
      '创作',
      '头脑风暴',
      '创意',
      '想象',
      '写一个',
      // Japanese
      '物語',
      '詩',
      '作曲',
      'ブレインストーム',
      '創造的',
      '想像',
      // Russian
      'история',
      'рассказ',
      'стихотворение',
      'сочинить',
      'сочини',
      'мозговой штурм',
      'творческий',
      'представить',
      'придумай',
      'напиши',
      // German
      'geschichte',
      'gedicht',
      'komponieren',
      'brainstorming',
      'kreativ',
      'vorstellen',
      'schreibe',
      'erzählung',
      // Spanish
      'historia',
      'poema',
      'componer',
      'lluvia de ideas',
      'creativo',
      'imaginar',
      'escribe',
      // Portuguese
      'história',
      'poema',
      'compor',
      'criativo',
      'imaginar',
      'escreva',
      // Korean
      '이야기',
      '시',
      '작곡',
      '브레인스토밍',
      '창의적',
      '상상',
      '작성',
      // Arabic
      'قصة',
      'قصيدة',
      'تأليف',
      'عصف ذهني',
      'إبداعي',
      'تخيل',
      'اكتب',
    ],
  },
  {
    kind: 'keyword',
    name: 'questionComplexity',
    weight: 0.03,
    direction: 'up',
    keywords: [
      // English
      'how does x relate to y',
      'what are the implications',
      'why would',
      'what happens if',
      'under what conditions',
      'how would you approach',
      'what is the relationship between',
      // Chinese
      '如何关联',
      '有什么影响',
      '为什么会',
      '如果会怎样',
      '在什么条件下',
      // Japanese
      'どのように関連',
      '影響は何',
      'なぜ',
      'もし何が起こる',
      'どのような条件',
      // Russian
      'как связано',
      'какие последствия',
      'почему бы',
      'что будет если',
      'при каких условиях',
      'как бы вы подошли',
      // German
      'wie hängt zusammen',
      'welche auswirkungen',
      'warum würde',
      'was passiert wenn',
      'unter welchen bedingungen',
      // Spanish
      'cómo se relaciona',
      'cuáles son las implicaciones',
      'por qué',
      'qué pasa si',
      'bajo qué condiciones',
      // Portuguese
      'como se relaciona',
      'quais são as implicações',
      'por que',
      'o que acontece se',
      'sob quais condições',
      // Korean
      '어떻게 관련',
      '어떤 영향',
      '왜',
      '만약 무슨 일이',
      '어떤 조건에서',
      // Arabic
      'كيف يرتبط',
      'ما هي التداعيات',
      'لماذا',
      'ماذا يحدث إذا',
      'تحت أي ظروف',
    ],
  },
  {
    kind: 'keyword',
    name: 'imperativeVerbs',
    weight: 0.02,
    direction: 'up',
    keywords: [
      // English
      'build',
      'create',
      'update',
      'deploy',
      'send',
      'check',
      'run',
      'install',
      'configure',
      'set up',
      'launch',
      'publish',
      'submit',
      'execute',
      'start',
      'stop',
      'restart',
      'delete',
      'remove',
      'review',
      'optimize',
      'scan',
      // Chinese
      '构建',
      '创建',
      '实现',
      '设计',
      '开发',
      '生成',
      '部署',
      '配置',
      '设置',
      // Japanese
      '構築',
      '作成',
      '実装',
      '設計',
      '開発',
      '生成',
      'デプロイ',
      '設定',
      // Russian
      'построить',
      'построй',
      'создать',
      'создай',
      'реализовать',
      'реализуй',
      'спроектировать',
      'разработать',
      'разработай',
      'сгенерировать',
      'сгенерируй',
      'развернуть',
      'разверни',
      'настроить',
      'настрой',
      // German
      'erstellen',
      'bauen',
      'implementieren',
      'entwerfen',
      'entwickeln',
      'konstruieren',
      'generieren',
      'bereitstellen',
      'konfigurieren',
      'einrichten',
      // Spanish
      'construir',
      'crear',
      'implementar',
      'diseñar',
      'desarrollar',
      'generar',
      'desplegar',
      'configurar',
      // Portuguese
      'construir',
      'criar',
      'implementar',
      'projetar',
      'desenvolver',
      'gerar',
      'implantar',
      'configurar',
      // Korean
      '구축',
      '생성',
      '구현',
      '설계',
      '개발',
      '배포',
      '설정',
      // Arabic
      'بناء',
      'إنشاء',
      'تنفيذ',
      'تصميم',
      'تطوير',
      'توليد',
      'نشر',
      'إعداد',
    ],
  },
  {
    kind: 'keyword',
    name: 'outputFormat',
    weight: 0.02,
    direction: 'up',
    keywords: [
      // English
      'as json',
      'in json',
      'as yaml',
      'in yaml',
      'as csv',
      'markdown',
      'as a table',
      'in a table',
      'as xml',
      'formatted as',
      'output as',
      'return as',
      'in the format',
      'json',
      'yaml',
      'xml',
      'schema',
      'structured',
      // Chinese
      '表格',
      '格式化为',
      '结构化',
      // Japanese
      'テーブル',
      'フォーマット',
      '構造化',
      // Russian
      'таблица',
      'форматировать как',
      'структурированный',
      // German
      'tabelle',
      'formatieren als',
      'strukturiert',
      // Spanish
      'tabla',
      'formatear como',
      'estructurado',
      // Portuguese
      'tabela',
      'formatar como',
      'estruturado',
      // Korean
      '테이블',
      '형식',
      '구조화',
      // Arabic
      'جدول',
      'تنسيق',
      'منظم',
    ],
  },
  {
    kind: 'keyword',
    name: 'domainSpecificity',
    weight: 0.05,
    direction: 'up',
    keywords: [
      // English
      'p-value',
      'confidence interval',
      'regression',
      'hipaa',
      'gdpr',
      'sec filing',
      'tort',
      'liability',
      'fiduciary',
      'amortization',
      'eigenvalue',
      'fourier transform',
      'bayesian',
      'posterior',
      'genome',
      'phenotype',
      'pharmacokinetics',
      'distribution',
      'probability',
      'statistics',
      'calculate',
      'quantum',
      'fpga',
      'vlsi',
      'risc-v',
      'asic',
      'photonics',
      'genomics',
      'proteomics',
      'topological',
      'homomorphic',
      'zero-knowledge',
      'lattice-based',
      // Chinese
      '量子',
      '光子学',
      '基因组学',
      '蛋白质组学',
      '拓扑',
      '同态',
      '零知识',
      '格密码',
      // Japanese
      '量子',
      'フォトニクス',
      'ゲノミクス',
      'トポロジカル',
      // Russian
      'квантовый',
      'фотоника',
      'геномика',
      'протеомика',
      'топологический',
      'гомоморфный',
      'с нулевым разглашением',
      'на основе решёток',
      // German
      'quanten',
      'photonik',
      'genomik',
      'proteomik',
      'topologisch',
      'homomorph',
      'gitterbasiert',
      // Spanish
      'cuántico',
      'fotónica',
      'genómica',
      'proteómica',
      'topológico',
      'homomórfico',
      // Portuguese
      'quântico',
      'fotônica',
      'genômica',
      'proteômica',
      'topológico',
      'homomórfico',
      // Korean
      '양자',
      '포토닉스',
      '유전체학',
      '위상',
      '동형',
      // Arabic
      'كمي',
      'ضوئيات',
      'جينوميات',
      'طوبولوجي',
      'تماثلي',
    ],
  },
  {
    kind: 'keyword',
    name: 'agenticTasks',
    weight: 0.03,
    direction: 'up',
    keywords: [
      // English
      'triage',
      'audit',
      'investigate',
      'monitor',
      'orchestrate',
      'coordinate',
      'schedule',
      'prioritize',
      'delegate',
      'batch process',
      'scan all',
      'check all',
      'review all',
      'update all',
      'migrate',
      'remediation',
      'read file',
      'read the file',
      'edit',
      'modify',
      'execute',
      'deploy',
      'fix',
      'debug',
      'verify',
      'confirm',
      // Chinese
      '读取文件',
      '查看',
      '打开',
      '编辑',
      '修改',
      '更新',
      '创建',
      '执行',
      '部署',
      '安装',
      '第一步',
      '第二步',
      '修复',
      '调试',
      '直到',
      '确认',
      '验证',
      // Spanish
      'leer archivo',
      'editar',
      'modificar',
      'actualizar',
      'ejecutar',
      'desplegar',
      'instalar',
      'arreglar',
      'depurar',
      'verificar',
      // Portuguese
      'ler arquivo',
      'editar',
      'modificar',
      'atualizar',
      'executar',
      'implantar',
      'instalar',
      'corrigir',
      'depurar',
      'verificar',
      // Korean
      '파일 읽기',
      '편집',
      '수정',
      '업데이트',
      '실행',
      '배포',
      '설치',
      '디버그',
      '확인',
      // Arabic
      'قراءة ملف',
      'تحرير',
      'تعديل',
      'تحديث',
      'تنفيذ',
      'نشر',
      'تثبيت',
      'إصلاح',
      'تصحيح',
      'تحقق',
    ],
  },
  {
    kind: 'keyword',
    name: 'relay',
    weight: 0.02,
    direction: 'down',
    keywords: [
      // English
      'forward to',
      'escalate',
      'transfer to',
      'pass along',
      'relay',
      'just say',
      'tell them',
      'send this to',
      'notify',
      'ping',
      'acknowledge',
      'confirm receipt',
      'mark as read',
      // Chinese
      '转发给',
      '升级',
      '转交',
      '传达',
      '通知',
      '确认收到',
      // Japanese
      '転送',
      'エスカレート',
      '通知',
      '確認',
      // Russian
      'переслать',
      'перенаправить',
      'эскалировать',
      'передать',
      'уведомить',
      // German
      'weiterleiten',
      'eskalieren',
      'übertragen',
      'benachrichtigen',
      // Spanish
      'reenviar',
      'escalar',
      'transferir',
      'notificar',
      // Portuguese
      'encaminhar',
      'escalar',
      'transferir',
      'notificar',
      // Korean
      '전달',
      '에스컬레이션',
      '전송',
      '알림',
      // Arabic
      'إعادة توجيه',
      'تصعيد',
      'نقل',
      'إبلاغ',
    ],
  },
];

// ── Structural dimensions (9) ──────────────────────────────────────────────

const DEFAULT_STRUCTURAL_DIMENSIONS: DimensionDef[] = [
  { kind: 'structural', name: 'tokenCount', weight: 0.05, direction: 'up' },
  { kind: 'structural', name: 'nestedListDepth', weight: 0.03, direction: 'up' },
  { kind: 'structural', name: 'conditionalLogic', weight: 0.03, direction: 'up' },
  { kind: 'structural', name: 'codeToProse', weight: 0.02, direction: 'up' },
  { kind: 'structural', name: 'constraintDensity', weight: 0.03, direction: 'up' },
  { kind: 'structural', name: 'expectedOutputLength', weight: 0.04, direction: 'up' },
  { kind: 'structural', name: 'repetitionRequests', weight: 0.02, direction: 'up' },
  { kind: 'structural', name: 'toolCount', weight: 0.04, direction: 'up' },
  { kind: 'structural', name: 'conversationDepth', weight: 0.03, direction: 'up' },
];

// ---------------------------------------------------------------------------
// Default scoring config
// ---------------------------------------------------------------------------

export const DEFAULT_SCORING_CONFIG: ScoringConfig = {
  dimensions: [...DEFAULT_KEYWORD_DIMENSIONS, ...DEFAULT_STRUCTURAL_DIMENSIONS],
  boundaries: {
    simpleStandard: -0.1,
    standardComplex: 0.08,
    complexReasoning: 0.35,
  },
  overrides: {
    reasoningKeywordMin: 2,
    largeContextTokens: 50_000,
    shortMessageChars: 50,
    structuredOutputMinTier: 'STANDARD',
  },
  confidenceSteepness: 8,
  confidenceThreshold: 0.45,
  systemPromptScoring: false,
  scoringMessageWindow: 3,
  tokenCountThresholds: { simple: 50, complex: 500 },
};

// ---------------------------------------------------------------------------
// Default classifier config
// ---------------------------------------------------------------------------

export const DEFAULT_CLASSIFIER_CONFIG: ClassifierConfig = {
  enabled: false,
  model: 'gpt-4o-mini',
  maxTokens: 10,
  temperature: 0,
  truncationChars: 500,
  cacheTtlMs: 3_600_000, // 1 hour
};

// ---------------------------------------------------------------------------
// Default dedup config
// ---------------------------------------------------------------------------

export const DEFAULT_DEDUP_CONFIG: DedupConfig = {
  enabled: true,
  ttlMs: 30_000, // 30 seconds
  maxBodySize: 1_048_576, // 1MB
};

// ---------------------------------------------------------------------------
// Full default config
// ---------------------------------------------------------------------------

export const DEFAULT_MODEL_ROUTING_CONFIG: ModelRoutingConfig = {
  enabled: true,
  port: 9000,
  targetBaseUrl: getOpenAIBaseUrl() || 'https://api.openai.com',
  targetApiKey: getOpenAIApiKey() || '',

  scoring: DEFAULT_SCORING_CONFIG,
  tiersByProfile: PROFILE_CONFIGS,
  providers: {},
  classifier: DEFAULT_CLASSIFIER_CONFIG,
  dedup: DEFAULT_DEDUP_CONFIG,
  exclusions: [],

  // Phase 4: Session Intelligence
  momentum: DEFAULT_MOMENTUM_CONFIG,
  session: DEFAULT_SESSION_STORE_CONFIG,
  defaultProfile: 'eco',

  // Phase 5: Production Hardening
  responseCache: DEFAULT_RESPONSE_CACHE_CONFIG,
  costAlerts: DEFAULT_COST_ALERT_CONFIG,
  providerCache: DEFAULT_PROVIDER_CACHE_CONFIG,
};
